apiVersion: v1
metadata:
  name: nginx-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>A simple HTML document</title>
    </head>
    <body>
        <p>This is Production Deployment!<p>
    </body>
    </html>
kind: ConfigMap
