apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: prod
namespace: prod
nameSuffix: -prod
resources:
  - ../../base
  - configmap.yaml
replicas:
  - count: 1
    name: nginx
images:
  - name: nginx
    newTag: "1.24"
