apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   name: nginx
commonLabels:
  # app: nginx
  env: dev
#setting namepace
namespace: dev
#setting a name suffix to be appended to the deployment.yaml name
nameSuffix: -dev
resources:
  ../../base
replicas:
- name: nginx
  count: 1
images:
- name: nginx
  newTag: 1.25
