apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      env: dev
#setting namepace
namespace: dev
#setting a name suffix to be appended to the deployment.yaml name
nameSuffix: -dev
resources:
  - ../../base
replicas:
  - count: 1
    name: nginx
images:
  - name: nginx
    newTag: "1.25"
