apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      env: staging
namespace: staging
nameSuffix: -staging
resources:
  - ../../base
  - configmap.yaml
replicas:
  - name: nginx
    count: 1
images:
  - name: nginx
    newTag: '1.24'
